### ISSUE TITLE
URI init with try-catch

### ISSUE THREAD

**Issue by maxsupermanhd** [ben-zen/uri-library#8]
How to keep uri after try-catch without empty constructor?
```
uri request;
try {
  request = uri(std::string(buf));
  auto requestParams = request.get_query_dictionary();
} catch (std::invalid_argument &e) {
  ...
}
request.get_path();
```
Following example is not working, I don't want to wrap whole logic into try-catch...

**Comment by ben-zen** [comment]
This sounds like a good case for a helper function along the lines of
```
std::optional<uri> try_parse(std::string x) {
  try {
    return uri{x};
  } catch (std::invalid_argument) {
    return std::nullopt;
  }
}
```
When I wrote this library, I explicitly didn't have the concept of a "null URI" in the form of an empty constructor, because the concept of it doesn't make sense. In this situation, I'm curious how you'd handle the failure case in the catch block, or if it would just be a matter of returning there. In that case, calling this code would look like:
```
auto request_opt = try_parse(std::string{buf});
if (!request_opt) {
  return;
}
// otherwise unwrap the request and proceed
```

**Comment by maxsupermanhd** [comment]
Oh, std::optional... Ok, thanks, I did not thought it can be used here.
